### ISSUE TITLE
My name showed up in CUSTOMER_TEXT.csv

### ISSUE THREAD

**Issue by coo1k** [SAP-samples/hana-xsa-live-reporting#1]
Why is my name showing up in this file? Where is this file sourced from? It’s showing up in Google search results.

CUSTOMER_TEXT.csv

**Comment by jung-thomas** [comment]
This is just randomly generated demo data. It doesn't refer to any individual or real system data. It is part of the SAP IDES (Internet Demo and Evaluation System).
